import Head from 'next/head'

import { API_KEY } from "src/constants";

export default function Home() {
  return (
    <>
      <Head>
        <title>Error</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex justify-center items-center flex-col flex-1 gap-2'>
        {API_KEY}
      </div>
    </>
  )
}
