import Head from 'next/head'
import ActionButton from '@components/ItemAction'
import { useState } from 'react';

export default function Home() {

  const [addItem, setAddItem] = useState({
    productName: "", 
    productPrice: "",
    productStockAmount: "",
    productDescription: "",
  })
  const [addBooking, setAddBooking] = useState({
    userId: "", 
    amount: "",
    productId: "",
  })
  const [addBookingResponse, setAddBookingResponse] = useState(null)
  const [addResponse, setAddResponse] = useState(null)
  const [getItems, setGetItems] = useState([]);
  const [getItemsBooked, setGetItemsBooked] = useState([]);
  const [deleteItemId, setDeleteItemId] = useState({
    id: ""
  });
  const [deleteResponse, setDeleteResponse] = useState(null);

  const handleAdd = async () => {
    try {
      const response = await fetch('https://7qtlrfjn2i.execute-api.us-east-1.amazonaws.com/products', {
        method: 'POST',
        body: JSON.stringify(addItem),
      });
      const data = await response.json()
      setAddResponse(data);
      console.log('Added item:', data);
      setAddItem({
        productName: "", 
        productPrice: "",
        productStockAmount: "",
        productDescription: "",
      })
    } catch (error) {
      console.error('Error adding item:', error)
    }
  }

  const handleAddBookings = async () => {
    try {
      const response = await fetch(`https://7qtlrfjn2i.execute-api.us-east-1.amazonaws.com/products/${addBooking.productId}/bookings`, {
        method: 'POST',
        body: JSON.stringify(addBooking),
      });
      const data = await response.json()
      setAddBookingResponse(data);
      console.log('Added item:', data);
      setAddItem({
        userId: "", 
        amount: "",
        productId: "",
      })
    } catch (error) {
      console.error('Error adding item:', error)
    }
  }

  const handleGet = async () => {
    try {
      const response = await fetch('https://7qtlrfjn2i.execute-api.us-east-1.amazonaws.com/products');
      const data = await response.json();
      setGetItems(data.products)
      console.log('Fetched items:', data);
    } catch (error) {
      console.error('Error fetching items:', error);
    }
  };

  const handleGetBookings = async () => {
    try {
      const response = await fetch('https://7qtlrfjn2i.execute-api.us-east-1.amazonaws.com/bookings');
      const data = await response.json();
      setGetItemsBooked(data.products)
      console.log('Fetched items:', data);
    } catch (error) {
      console.error('Error fetching items:', error);
    }
  };

  const handleDelete = async () => {
    try {
      const response = await fetch(`https://7qtlrfjn2i.execute-api.us-east-1.amazonaws.com/products/${deleteItemId.id}`, {
        method: 'DELETE',
      });
      if (response.ok) {
        setDeleteResponse({ success: true, id: deleteItemId.id });
        console.log('Deleted item with ID:', deleteItemId);
        setDeleteItemId({id: ""})
      } else {
        throw new Error('Failed to delete item');
      }
    } catch (error) {
      console.error('Error deleting item:', error);
    }
  };

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex flex-row w-screen h-screen'>
        <ActionButton 
          buttonText="Add product" 
          buttonColor="#85c1e9" 
          hasInput={true} 
          onButtonClick={handleAdd} 
          placeholder="Enter"
          inputValue={addItem}
          setInputValue={setAddItem}
          addResponse={addResponse}
        />
        <ActionButton 
          buttonText="Get products" 
          buttonColor="#239b56" 
          hasInput={false} 
          onButtonClick={handleGet}
          hasBorderLeft={true}
          hasBorderRight={true}
          getResponse={getItems}
        />
        <ActionButton 
          buttonText="Delete product" 
          buttonColor="#e74c3c" 
          hasInput={true} 
          onButtonClick={handleDelete}
          placeholder="Enter"
          inputValue={deleteItemId}
          setInputValue={setDeleteItemId}
          deleteResponse={deleteResponse}
        />

        <ActionButton 
          buttonText="Book product" 
          buttonColor="#f39c12"
          hasBorderLeft={true}
          hasBorderRight={true}
          hasInput={true} 
          onButtonClick={handleAddBookings} 
          placeholder="Enter"
          inputValue={addBooking}
          setInputValue={setAddBooking}
          addResponse={addBookingResponse}
        />

        <ActionButton 
          buttonText="Get bookings" 
          buttonColor="#a569bd" 
          hasInput={false} 
          onButtonClick={handleGetBookings}
          hasBorderRight={true}
          getResponse={getItemsBooked}
          isGetBooking={true}
        />
      </div>
    </>
  )
}
